### ISSUE TITLE
About Phoneme/Viseme Tables

### ISSUE THREAD

**Issue by devanshbatra04** [awsdocs/amazon-polly-developer-guide#12]
This is more of a question than an issue. 

There are Phoneme/Viseme tables available at https://docs.aws.amazon.com/polly/latest/dg/ref-phoneme-tables-shell.html which are supported by Amazon Polly. 

I require a text to speech speech system for my research. I want to select certain words which will be spoken with exclusively with certain visemes (like T, @, O, etc) in various languages and generate these sounds of words using amazon polly to further study it in speech signal domain. 

However, Hindi, which is a very important language I wish to include does not have Phoneme/Viseme mapping info on the website. Only phonemes (viseme column is absent from the table) are available. I am willing to generate the table myself but what are the visemes which you support? For ex: some linguists say there are 13 visemes others say there are 16 (or more). Also some linguistics may map a phoneme to a different one than other. 

How were these visemes shortlisted. Perhaps a citation to the original publication would be helpful.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
