### ISSUE TITLE
AWS for Wordpress plugin no longer available

### ISSUE THREAD

**Issue by dreamerdad** [awsdocs/amazon-polly-developer-guide#14]
The AWS for Wordpress plugin, referenced in the help doc at https://docs.aws.amazon.com/polly/latest/dg/WordPressPlugin-install.html, is no longer available via Wordpress. See https://wordpress.org/plugins/  It is also not available here: https://github.com/awslabs/aws-for-wordpress

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
