### ISSUE TITLE
[Errno 13] Permission denied: 'hello.mp3'

### ISSUE THREAD

**Issue by majikbyte** [awsdocs/amazon-polly-developer-guide#16]
Hello, 

Just getting started with AWS in general so not sure what's going on here. 

I ran the Polly sample command in bash to get started. 

aws polly synthesize-speech \
    --output-format mp3 \
    --voice-id Joanna \
    --text 'Hello, my name is Joanna. I learned about the W3C on 10/3 of last year.' \
    hello.mp3

Returned this error: [Errno 13] Permission denied: 'hello.mp3'

I tried redirecting the file using > ~/hello.mp3 and that did not work.
 
I also thought I tried changing permissions on various files and directories using sudo chmod +x, but I may have missed something there. 

Ubuntu 22.10

********Update

I reconfigured aws using sudo aws configure.  

I then ran the Polly command aws using sudo and now it works fine. 

Thanks,

Matthew

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
