### ISSUE TITLE
Support for mixed languages

### ISSUE THREAD

**Issue by PengFei-io** [awsdocs/amazon-polly-developer-guide#17]
Can a text with both Chinese and English support voice conversion? Without specifying a language type。And you don't need to use an SSML tag to set whether it's in Chinese or English

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
