### ISSUE TITLE
Code snippet rendered wrong

### ISSUE THREAD

**Issue by HatBeardMe** [awsdocs/amazon-polly-developer-guide#8]
looks correct in source at doc_source/get-started-what-next.md

but at https://docs.aws.amazon.com/polly/latest/dg/get-started-what-next.html there are two extra comments on lines 30 and 35
![image](https://user-images.githubusercontent.com/9095361/73565516-b2139180-442f-11ea-862c-69ab51436650.png)

**Comment by HoYoung1** [comment]
I also saw extra comments mentioned by @HatBeardMe 
Now it has been modified like this, but the indent is still wrong

![image](https://user-images.githubusercontent.com/35159888/89764818-15455580-db30-11ea-8d1b-e5a1ab8ef78d.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
